drop table if exists reedos.sys_dict_data;
create table reedos.sys_dict_data
(
    dict_code   bigint auto_increment comment '字典编码'
        primary key,
    dict_sort   int(4)       default 0   null comment '字典排序',
    dict_label  varchar(100) default ''  null comment '字典标签',
    dict_value  varchar(100) default ''  null comment '字典键值',
    dict_type   varchar(100) default ''  null comment '字典类型',
    css_class   varchar(100)             null comment '样式属性（其他样式扩展）',
    list_class  varchar(100)             null comment '表格回显样式',
    is_default  char         default 'N' null comment '是否默认（Y是 N否）',
    status      char         default '0' null comment '状态（0正常 1停用）',
    create_by   varchar(64)  default ''  null comment '创建者',
    create_time datetime                 null comment '创建时间',
    update_by   varchar(64)  default ''  null comment '更新者',
    update_time datetime                 null comment '更新时间',
    remark      varchar(500)             null comment '备注'
)
    comment '字典数据表';

insert into reedos.sys_dict_data (dict_code, dict_sort, dict_label, dict_value, dict_type, css_class, list_class, is_default, status, create_by, create_time, update_by, update_time, remark)
values (1, 1, '男', '0', 'sys_user_sex', '', '', 'Y', '0', 'admin', sysdate(), '', null, '性别男'),
       (2, 2, '女', '1', 'sys_user_sex', '', '', 'N', '0', 'admin', sysdate(), '', null, '性别女'),
       (3, 3, '未知', '2', 'sys_user_sex', '', '', 'N', '0', 'admin', sysdate(), '', null, '性别未知'),
       (4, 1, '显示', '0', 'sys_show_hide', '', 'primary', 'Y', '0', 'admin', sysdate(), '', null, '显示菜单'),
       (5, 2, '隐藏', '1', 'sys_show_hide', '', 'danger', 'N', '0', 'admin', sysdate(), '', null, '隐藏菜单'),
       (6, 1, '正常', '0', 'sys_normal_disable', '', 'primary', 'Y', '0', 'admin', sysdate(), '', null, '正常状态'),
       (7, 2, '停用', '1', 'sys_normal_disable', '', 'danger', 'N', '0', 'admin', sysdate(), '', null, '停用状态'),
       (8, 1, '是', 'Y', 'sys_yes_no', '', 'primary', 'Y', '0', 'admin', sysdate(), '', null, '系统默认是'),
       (9, 2, '否', 'N', 'sys_yes_no', '', 'danger', 'N', '0', 'admin', sysdate(), '', null, '系统默认否'),
       (10, 1, '通知', '1', 'sys_notice_type', '', 'warning', 'Y', '0', 'admin', sysdate(), '', null, '通知'),
       (11, 2, '公告', '2', 'sys_notice_type', '', 'success', 'N', '0', 'admin', sysdate(), '', null, '公告'),
       (12, 1, '正常', '0', 'sys_notice_status', '', 'primary', 'Y', '0', 'admin', sysdate(), '', null, '正常状态'),
       (13, 2, '关闭', '1', 'sys_notice_status', '', 'danger', 'N', '0', 'admin', sysdate(), '', null, '关闭状态'),
       (14, 99, '其他', '0', 'sys_oper_type', '', 'info', 'N', '0', 'admin', sysdate(), '', null, '其他操作'),
       (15, 1, '新增', '1', 'sys_oper_type', '', 'info', 'N', '0', 'admin', sysdate(), '', null, '新增操作'),
       (16, 2, '修改', '2', 'sys_oper_type', '', 'info', 'N', '0', 'admin', sysdate(), '', null, '修改操作'),
       (17, 3, '删除', '3', 'sys_oper_type', '', 'danger', 'N', '0', 'admin', sysdate(), '', null, '删除操作'),
       (18, 4, '授权', '4', 'sys_oper_type', '', 'primary', 'N', '0', 'admin', sysdate(), '', null, '授权操作'),
       (19, 5, '导出', '5', 'sys_oper_type', '', 'warning', 'N', '0', 'admin', sysdate(), '', null, '导出操作'),
       (20, 6, '导入', '6', 'sys_oper_type', '', 'warning', 'N', '0', 'admin', sysdate(), '', null, '导入操作'),
       (21, 7, '强退', '7', 'sys_oper_type', '', 'danger', 'N', '0', 'admin', sysdate(), '', null, '强退操作'),
       (22, 8, '生成代码', '8', 'sys_oper_type', '', 'warning', 'N', '0', 'admin', sysdate(), '', null, '生成操作'),
       (23, 9, '清空数据', '9', 'sys_oper_type', '', 'danger', 'N', '0', 'admin', sysdate(), '', null, '清空操作'),
       (24, 1, '成功', '0', 'sys_common_status', '', 'primary', 'N', '0', 'admin', sysdate(), '', null, '正常状态'),
       (25, 2, '失败', '1', 'sys_common_status', '', 'danger', 'N', '0', 'admin', sysdate(), '', null, '停用状态'),
       (26, 1, '正常', '0', 'auto_job_status', '', 'primary', 'Y', '0', 'admin', sysdate(), '', null, '正常状态'),
       (27, 2, '暂停', '1', 'auto_job_status', '', 'danger', 'N', '0', 'admin', sysdate(), '', null, '停用状态'),
       (28, 1, '默认', 'DEFAULT', 'auto_job_group', '', '', 'Y', '0', 'admin', sysdate(), '', null, '默认分组'),
       (29, 2, '系统', 'SYSTEM', 'auto_job_group', '', '', 'N', '0', 'admin', sysdate(), '', null, '系统分组'),
       (30, 1, 'mysql', 'com.mysql.cj.jdbc.Driver', 'auto_datasource_driver', null, null, 'Y', '0', 'admin', sysdate(), '', null, null),
       (31, 1, '自动化任务', '0', 'auto_job_type', null, null, 'Y', '0', 'admin', sysdate(), '', null, null),
       (32, 2, '已注册类方法调用', '1', 'auto_job_type', null, null, 'Y', '0', 'admin', sysdate(), '', null, null),
       (33, 1, '待审核', '0', 'audit_state', '', 'info', 'Y', '0', 'admin', sysdate(), 'ry', null, '待审核状态'),
       (34, 2, '审核通过', '1', 'audit_state', '', 'primary', 'N', '0', 'admin', sysdate(), 'ry', null, '审核通过状态'),
       (35, 3, '审核未通过', '2', 'audit_state', '', 'danger', 'N', '0', 'admin', sysdate(), 'admin', null, '未通过状态'),
       (100, 1, '人脸检测', 'faceDetect', 'ai_type', null, null, 'Y', '0', 'admin', sysdate(), '', null, null),
       (101, 2, '植物识别', 'plant', 'ai_type', null, null, 'Y', '0', 'admin', sysdate(), '', null, null),
       (102, 3, '银行卡识别', 'bankCard', 'ai_type', null, null, 'Y', '0', 'admin', sysdate(), '', null, null),
       (103, 4, '身份证识别', 'idCard', 'ai_type', null, null, 'Y', '0', 'admin', sysdate(), '', null, null),
       (104, 5, '车牌号识别', 'plate', 'ai_type', null, null, 'Y', '0', 'admin', sysdate(), '', null, null),
       (105, 6, '驾驶证识别', 'driver', 'ai_type', null, null, 'Y', '0', 'admin', sysdate(), '', null, null),
       (106, 7, '动物识别', 'animal', 'ai_type', null, null, 'Y', '0', 'admin', sysdate(), '', null, null),
       (107, 8, '车型识别', 'car', 'ai_type', '', '', 'Y', '0', 'admin', sysdate(), 'admin', null, ''),
       (108, 9, '菜品识别', 'dish', 'ai_type', null, null, 'Y', '0', 'admin', sysdate(), '', null, null),
       (109, 10, '通用文字识别', 'general_basic', 'ai_type', null, null, 'Y', '0', 'admin', null, '', null, null),
       (110, 1, '头条', 'top', 'article_region', '', '', 'N', '0', 'admin', sysdate(), '', null, ''),
       (111, 2, '热门', 'hot', 'article_region', '', '', 'N', '0', 'admin', sysdate(), '', null, ''),
       (112, 3, '精选推荐', 'recommend', 'article_region', '', '', 'N', '0', 'admin', sysdate(), '', null, ''),
       (113, 4, '评论最多', 'most_comment', 'article_region', '', '', 'N', '0', 'admin', sysdate(), '', null, ''),
       (115, 1, '系统标签', 's', 'tags_type', null, 'primary', 'Y', '0', '', null, '', null, null),
       (116, 2, '个人标签', 'p', 'tags_type', null, 'danger', 'N', '0', '', null, '', null, null),
       (117, 3, '博客标签', 'blogTab', 'tags_type', null, 'success', 'N', '0', '', null, '', null, null),
       (118, 1, '多骨鱼', 'duoguyu', 'article_model', null, 'success', 'Y', '0', '', null, '', null, null),
       (119, 2, '其它', 'other', 'article_model', null, 'danger', 'N', '0', '', null, '', null, null),
       (120, 1, '未发送', '0', 'send_flag', '', 'info', 'Y', '0', 'admin', sysdate(), 'admin', null, ''),
       (121, 2, '已发送', '1', 'send_flag', '', 'success', 'N', '0', 'admin', sysdate(), 'admin', null, ''),
       (122, 1, '立即', '0', 'send_type', '', 'info', 'Y', '0', 'admin', sysdate(), 'admin', null, ''),
       (123, 2, '定时', '1', 'send_type', '', 'success', 'N', '0', 'admin', sysdate(), 'admin', null, ''),
       (124, 1, '草稿', '0', 'sys_available_status', '', 'primary', 'Y', '0', 'admin', sysdate(), 'ry', null, '草稿状态'),
       (126, 3, '待审核', '2', 'sys_available_status', '', 'primary', 'N', '0', 'admin', sysdate(), 'ry', null, '待审核状态'),
       (127, 1, '未使用', '0', 'use_state', '', 'primary', 'N', '0', 'admin', sysdate(), 'admin', null, ''),
       (128, 2, '使用中', '1', 'use_state', '', 'danger', 'Y', '0', 'admin', sysdate(), 'admin', null, ''),
       (129, 1, '图片', '1', 'material_type', '', 'success', 'Y', '0', 'admin', sysdate(), 'ry', null, '草稿状态'),
       (130, 2, '视频', '2', 'material_type', '', 'info', 'N', '0', 'admin', sysdate(), 'ry', null, '已审核状态'),
       (131, 3, '文本', '3', 'material_type', '', 'primary', 'N', '0', 'admin', sysdate(), 'ry', null, '待审核状态'),
       (132, 4, '音频', '4', 'material_type', '', 'danger', 'N', '0', 'admin', sysdate(), 'ry', null, '待审核状态'),
       (133, 5, '压缩', '5', 'material_type', '', 'warning', 'N', '0', 'admin', sysdate(), 'ry', null, '待审核状态'),
       (134, 6, '其它', '6', 'material_type', '', 'default', 'N', '0', 'admin', sysdate(), 'ry', null, '待审核状态'),
       (135, 1, '推送', 'urls', 'baidu_push_type', '', 'primary', 'Y', '0', 'admin', sysdate(), 'ry', null, '待审核状态'),
       (136, 2, '更新', 'update', 'baidu_push_type', '', 'info', 'N', '0', 'admin', sysdate(), 'ry', null, '待审核状态'),
       (137, 3, '删除', 'del', 'baidu_push_type', '', 'danger', 'N', '0', 'admin', sysdate(), 'ry', null, '待审核状态'),
       (138, 1, '相册', 'album', 'album_type', '', 'primary', 'Y', '0', 'admin', sysdate(), 'admin', '2019-11-16 18:24:37', ''),
       (139, 2, 'banner', 'banner', 'album_type', null, 'success', 'Y', '0', 'admin', sysdate(), '', null, null),
       (140, 1, '待执行', 'wait', 'spider_mission_status', null, 'info', 'Y', '0', 'admin', sysdate(), '', null, null),
       (141, 2, '执行中', 'running', 'spider_mission_status', null, 'success', 'N', '0', 'admin', sysdate(), '', null, null),
       (142, 3, '完成', 'done', 'spider_mission_status', null, 'primary', 'N', '0', 'admin', sysdate(), '', null, null),
       (143, 4, '错误', 'error', 'spider_mission_status', null, 'danger', 'N', '0', 'admin', sysdate(), '', null, null),
       (144, 1, '默认', 'DEFAULT', 'spider_exit_way', null, 'default', 'Y', '0', 'admin', sysdate(), '', null, null),
       (145, 2, '持续时间', 'DURATION', 'spider_exit_way', null, 'primary', 'N', '0', 'admin', sysdate(), '', null, null),
       (146, 3, '链接计数', 'URL_COUNT', 'spider_exit_way', null, 'success', 'N', '0', 'admin', sysdate(), '', null, null),
       (147, 1, 'Xpath', 'xpath', 'spider_extract_type', null, 'primary', 'Y', '0', 'admin', sysdate(), '', null, null),
       (148, 2, 'Css', 'css', 'spider_extract_type', null, 'success', 'N', '0', 'admin', sysdate(), '', null, null),
       (149, 3, '常量', 'constant', 'spider_extract_type', null, 'warning', 'N', '0', 'admin', sysdate(), '', null, null),
       (150, 1, '替换', 'replace', 'field_value_process_type', null, 'primary', 'Y', '0', 'admin', sysdate(), '', null, null),
       (151, 2, '截取之前', 'substrbefore', 'field_value_process_type', null, 'success', 'N', '0', 'admin', sysdate(), '', null, null),
       (152, 3, '截取之后', 'substrafter', 'field_value_process_type', null, 'info', 'N', '0', 'admin', sysdate(), '', null, null),
       (153, 1, '协议模板', 'xieyi', 'template_type', null, 'primary', 'Y', '0', 'admin', sysdate(), '', null, null),
       (154, 2, '邮件模板', 'email', 'template_type', null, 'success', 'Y', '0', 'admin', sysdate(), '', null, null),
       (155, 3, '短信模板', 'sms', 'template_type', null, null, 'Y', '0', 'admin', sysdate(), '', null, null),
       (156, 1, '系统通知', 'system', 'site_msg_type', null, 'primary', 'Y', '0', 'admin', sysdate(), '', null, null),
       (157, 2, '私信', 'private', 'site_msg_type', '', 'success', 'N', '0', 'admin', sysdate(), 'admin', null, ''),
       (159, 1, '文章评论', 'article', 'cms_comment_type', null, 'primary', 'Y', '0', 'admin', sysdate(), '', null, null),
       (160, 2, '书籍评论', 'book', 'cms_comment_type', null, 'success', 'N', '0', 'admin', sysdate(), '', null, null),
       (161, 3, '书籍章节评论', 'chapter', 'cms_comment_type', null, 'info', 'N', '0', 'admin', sysdate(), '', null, null),
       (162, 4, '系统留言', 'liuyan', 'cms_comment_type', null, 'warning', 'N', '0', 'admin', sysdate(), '', null, null),
       (163, 1, '免费', '0', 'cms_free', null, 'primary', 'Y', '0', 'admin', sysdate(), '', null, null),
       (164, 2, '收费', '1', 'cms_free', null, 'success', 'N', '0', 'admin', sysdate(), '', null, null),
       (165, 1, '直接下载', '0', 'cms_download_type', null, 'default', 'Y', '0', 'admin', sysdate(), '', null, null),
       (166, 2, '登录下载', '1', 'cms_download_type', null, 'success', 'N', '0', 'admin', sysdate(), '', null, null),
       (167, 3, '关注后下载', '2', 'cms_download_type', null, 'info', 'N', '0', 'admin', sysdate(), '', null, null),
       (168, 1, '积分支付', '1', 'cms_pay_type', null, 'primary', 'Y', '0', 'admin', sysdate(), '', null, null),
       (169, 2, '人民币支付', '2', 'cms_pay_type', null, 'success', 'N', '0', 'admin', sysdate(), '', null, null),
       (170, 1, '主题模板', '1', 'cms_resource_type', '', 'primary', 'Y', '0', 'admin', sysdate(), 'admin', null, ''),
       (171, 2, '小程序', '2', 'cms_resource_type', null, 'success', 'N', '0', 'admin', sysdate(), '', null, null),
       (172, 3, '软件', '3', 'cms_resource_type', '', 'info', 'N', '0', 'admin', sysdate(), 'admin', null, ''),
       (173, 1, '电脑', 'Computer', 'client_device_type', null, 'primary', 'Y', '0', 'admin', sysdate(), '', null, null),
       (174, 2, '手机', 'Mobile', 'client_device_type', null, 'success', 'N', '0', 'admin', sysdate(), '', null, null),
       (175, 3, '平板', 'Tablet', 'client_device_type', null, 'info', 'N', '0', 'admin', sysdate(), '', null, null),
       (176, 4, '未知设备', 'Unknown', 'client_device_type', null, 'warning', 'N', '0', 'admin', sysdate(), '', null, null),
       (177, 1, '公共', 'public', 'share_type', null, 'primary', 'Y', '0', 'admin', sysdate(), '', null, null),
       (178, 2, '会员', 'vip', 'share_type', '', 'success', 'N', '0', 'admin', sysdate(), 'admin', null, ''),
       (207, 9, '清空数据', '9', 'sys_oper_type', '', 'danger', 'N', '0', 'admin', sysdate(), '', null, '清空操作'),
       (208, 1, '成功', '0', 'sys_common_status', '', 'primary', 'N', '0', 'admin', sysdate(), '', null, '正常状态'),
       (209, 2, '失败', '1', 'sys_common_status', '', 'danger', 'N', '0', 'admin', sysdate(), '', null, '停用状态');